/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package VendingMachine;

import org.junit.Test;

import static org.junit.Assert.assertNotNull;

public class AppTest {

    @Test
    public void testGreeting() {
        App app = new App();
        assertNotNull(app);
    }
}
